# Generated by Django 6.0 on 2026-01-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gemini-pro', 'Gemini Pro'), ('llama-2', 'Llama 2 (Local)')], default='gpt-3.5-turbo', max_length=50, verbose_name='مدل انتخاب شده'),
        ),
    ]
