# Generated by Django 6.0 on 2026-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='users_photos/default.png', null=True, upload_to='users_photos/'),
        ),
    ]
